trigger:
- main'

pool:
  vmImage: ubuntu-latest

strategy:
  matrix:
#    Python310:
    Python311:
      python.version: '3.11'
#    Python312:
#      python.version: '3.12'
  maxParallel: '1'

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
    displayName: 'Use Python $(python.version)'

#- script: |
#      python -m pip install --upgrade pip
#      pip install -r requirements.txt
#      pip install build
#      pip install twine
#    displayName: 'Install dependencies'

  - script: |
      pip install build
      pip install twine
    displayName: 'Install build and twine'

  - script: |
      python -m build -w
    displayName: 'Python build'

  #- task: TwineAuthenticate@1
  #inputs:
  #  artifactFeed: 'carbje-osb/carls-feed'
  #displayName: 'Twine Authenticate'

  #- script: |
  #  python -m twine upload -r carls-feed --config-file $(PYPIRC_PATH) dist/*.whl
  #displayName: 'Upload to feed'

#  - task: ArchiveFiles@2
#    displayName: 'Archive files'
#    inputs:
#      rootFolderOrFile: $(System.DefaultWorkingDirectory)
#      includeRootFolder: false
#      archiveType: zip
#      archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId)-$(python.version).zip
#      replaceExistingArchive: true

#  - task: PublishBuildArtifacts@1
#    inputs:
#      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
#      ArtifactName: 'drop'
#      publishLocation: 'Container'

  #- script: |
  #    pip install pytest pytest-azurepipelines
  #    pytest
  #  displayName: 'pytest'
